dtbo-y += aux-i2c.dtbo \
            aux-onewire.dtbo \
            aux-spi.dtbo \
            aux-uart.dtbo \
            emmc.dtbo \
            icm20948.dtbo \
            imx290.dtbo \
            os08a10.dtbo \
            ov2312.dtbo \
            ar0234.dtbo \
            remote.dtbo \
            sdio.dtbo \
            wdt.dtbo \
            wifi-bt.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
