# This file is mainly for JeVois development team
#
# Most users would just: (replace VERSION by a version number, e.g., 1.22.0)
#   docker pull jevois/jevoispro-compile-modules:VERSION
#   cd jevoispro-sdk
#   ./docker/compile-modules-in-docker.sh
#
# JeVois team: To create the docker image:
#
# Install docker as described here (we chose the apt-based install for Ubuntu):
# https://docs.docker.com/engine/install/ubuntu/
#
# Then build with: docker build -t jevois/jevoispro-compile-modules:VERSION -f Dockerfile-compile-modules .
# Then push to docker hub: docker login && docker image push jevois/jevoispro-compile-modules:VERSION

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

# Update:
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade

# Use bash only to avoid env issues:
RUN ln -snf /bin/bash /bin/sh
SHELL ["/bin/bash", "-c"]

# Install base packages:
RUN apt-get -y install gpg locales ca-certificates sudo apt-utils systemctl

# Install jevois.usc.edu apt repo:
RUN gpg --keyserver keyserver.ubuntu.com --recv-keys DD24C027 && \
    gpg --export DD24C027 > /etc/apt/trusted.gpg.d/jevois.gpg
RUN echo "deb https://jevois.usc.edu/apt noble main" > /etc/apt/sources.list.d/jevois.list

# Update:
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade

# The jevoispro-sdk deb will pull in all needed dependencies:
RUN apt-get -y install hailort
RUN apt-get -y install jevoispro-sdk-dev

# Clean up:
RUN apt-get -y autoremove

# Generate a US locale:
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8' TERM=screen

# Get ready to run as the same user as the caller:
COPY with_the_same_user /
